### ISSUE TITLE
 Could not find control URL for AVTransport service.

### ISSUE THREAD

**Issue by franki29** [mill1000/i2s-upnp-bridge#11]
HI, me again. The Sonos have the AVTransport Service element in, but can not be found by the bridge.

Looks like the bridge is searching in the "wrong" tree for using sonos devices:

root > device >.deviceList > device> serviceList  while the bridge is searching in device->FirstChildElement("serviceList")

Sonos also have entries under root > device > serviceList, but unfortunately not the AVTransport information.

How can the bridge be modified to look under root > device >.deviceList > device> serviceList for the AVTransport information?

Thanks and best regards

Frank

**Comment by mill1000** [comment]
Hi Frank,

I'm looking at the description XML for your SYMFONISK Picture Frame. It appears the issue is because we don't handle nested devices.

Here we grab the very first device entry
https://github.com/mill1000/i2s-upnp-bridge/blob/9113d2fe3758daab52af55cbd96feb6de3009828/main/upnp_control.cpp#L150


I'd have to review the UPNP spec but I'm guessing the correct approach is iterate through each possible device and check it's `deviceType`.

**Comment by mill1000** [comment]
Hey Frank. Try the lastest commit. I was able to parse the description XML that you posted from your previous issue.

**Comment by franki29** [comment]
Hi, yes it is working now. Only the PCM1808 does not work yet, I will open a new issue.
Thanks and best regards
Frank
